# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("alert_type", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("severity", models.CharField(default="info", max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read", "created_at"], name="alerts_weath_user_id_9e3d8f_idx"),
                    models.Index(fields=["city", "alert_type", "created_at"], name="alerts_weath_city_4cb364_idx"),
                ],
            },
        ),
    ]
