# Generated by Django 6.0.7 on 2026-07-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weatheralert',
            new_name='alerts_weat_user_828c34_idx',
            old_name='alerts_weath_user_id_9e3d8f_idx',
        ),
        migrations.RenameIndex(
            model_name='weatheralert',
            new_name='alerts_weat_city_b2c0c4_idx',
            old_name='alerts_weath_city_4cb364_idx',
        ),
    ]
