# Generated by Django 6.0.7 on 2026-07-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('visibility', models.FloatField(default=0)),
                ('weather_condition', models.CharField(blank=True, max_length=255)),
                ('weather_icon', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'country'], name='weather_wea_city_2f5dbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius')),
                ('humidity', models.IntegerField(help_text='Humidity percentage (0-100)')),
                ('pressure', models.IntegerField(help_text='Atmospheric pressure in hPa')),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('wind_direction', models.IntegerField(help_text='Wind direction in degrees (0-360)')),
                ('visibility', models.IntegerField(help_text='Visibility in meters')),
                ('uv_index', models.FloatField(default=0)),
                ('cloud_coverage', models.IntegerField(help_text='Cloud coverage percentage (0-100)')),
                ('weather_condition', models.CharField(help_text='Weather condition (e.g., Clear, Rainy)', max_length=255)),
                ('weather_description', models.CharField(blank=True, max_length=255)),
                ('weather_icon', models.CharField(help_text='Icon code for frontend', max_length=100)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_weather', to='weather.weatherstation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_avg', models.FloatField()),
                ('humidity_avg', models.IntegerField()),
                ('pressure_avg', models.IntegerField()),
                ('wind_speed_avg', models.FloatField()),
                ('precipitation_total', models.FloatField(default=0)),
                ('weather_condition', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='weather.weatherstation')),
            ],
            options={
                'ordering': ['-recorded_date'],
                'indexes': [models.Index(fields=['station', 'recorded_date'], name='weather_wea_station_14f0a6_idx')],
                'unique_together': {('station', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.IntegerField()),
                ('cloud_coverage', models.IntegerField()),
                ('precipitation_chance', models.IntegerField(default=0, help_text='Probability of precipitation (0-100)')),
                ('precipitation_amount', models.FloatField(default=0, help_text='Expected precipitation in mm')),
                ('weather_condition', models.CharField(max_length=255)),
                ('weather_description', models.CharField(blank=True, max_length=255)),
                ('weather_icon', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='weather.weatherstation')),
            ],
            options={
                'ordering': ['forecast_time'],
                'indexes': [models.Index(fields=['station', 'forecast_time'], name='weather_hou_station_75e897_idx')],
                'unique_together': {('station', 'forecast_time')},
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('humidity_avg', models.IntegerField()),
                ('wind_speed_avg', models.FloatField()),
                ('precipitation_chance', models.IntegerField(default=0)),
                ('precipitation_amount', models.FloatField(default=0, help_text='Expected precipitation in mm')),
                ('weather_condition', models.CharField(max_length=255)),
                ('weather_description', models.CharField(blank=True, max_length=255)),
                ('weather_icon', models.CharField(max_length=100)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('uv_index', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='weather.weatherstation')),
            ],
            options={
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['station', 'forecast_date'], name='weather_dai_station_c44eaa_idx')],
                'unique_together': {('station', 'forecast_date')},
            },
        ),
    ]
